export const MESSAGE_CODE = {
  MSG_001: '{property} phải nhỏ hơn {max} ký tự',
  MSG_002: '{property} phải có ít nhất {min} ký tự',
  MSG_003: '{property} không được để trống',
  MSG_004: '{property} phải có ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường, số và ký tự đặc biệt',
  MSG_005: '{property} không khớp với mật khẩu',
  MSG_006: '{property} chỉ được bao gồm alphabet và số',
  MSG_007: '{property} chỉ được bao gồm alphabet và khoảng trống',
  MSG_009: '{property} phải là số nguyên',
  MSG_010: '{property} sai định dạng ',
  MSG_015: '{property} không hỗ trợ emoji',
  MSG_011: '{property} không được vượt quá 255 ký tự',
  MSG_016: 'Vui lòng chọn ít nhất 1 danh mục',
  MSG_014: 'Người dùng không tồn tại',
  MSG_024: 'Một email khôi phục mật khẩu đã được gửi tới email của bạn',
}
export const MESSAGE_STATUS = {
  LOGIN_FAILED: 'Đăng nhập thất bại',
  ACCESS_DENIED: 'Bạn không có quyền truy cập!',
  REGISTER_SUCCESS: 'Đăng ký thành công!.',
  REGISTER_FAILED: 'Đăng ký không thành công!.',
  LOGIN_SUCCESS: 'Đăng nhập thành công!',
  LOGOUT_SUCCESS: 'Đăng xuất thành công!',
  PASSWORD_RESET_SUCCESS: 'Đặt lại mật khẩu thành công!',
  PASSWORD_CHANGE_SUCCESS: 'Đổi mật khẩu thành công!',
  PASSWORD_MISMATCH: 'Mật khẩu không khớp!',
  INTERNAL_SERVER_ERROR: 'Lỗi hệ thống, vui lòng thử lại sau!',
  INVALID_CREDENTIALS: 'Thông tin không hợp lệ',
  CONFLICT: 'Thông tin đã tồn tại!',
  NOT_FOUND: 'Không tìm thấy trang!',
  UPDATED_SUCCESS: '{property} cập nhật thành công!',
  DELETE_SUCCESS: '{property} xóa thành công!',
  CREATE_SUCCESS: '{property} thêm thành công!',
  UPDATED_FAILED: '{property} cập nhật thất bại!',
  RESET_SUCCESS: 'Yêu cầu reset  {property} thành công!',
}
export const CODE_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
}
